eval:
  eval_datasets: null
  json_datasets:
  - name: mean
    solutions: json/arc-agi_training_solutions.json
    challenges: json/arc-agi_training_challenges.json
    only_n_tasks: 5
    num_tasks_to_show: 5
  test_datasets:
  - name: arc_train_all_mean
    length: 64
    generator: ARC
    num_pairs: 4
    batch_size: 16
    num_tasks_to_show: 32
    task_generator_kwargs: null
  - name: arc_train_mean
    length: 64
    generator: ARC
    num_pairs: 4
    batch_size: 16
    num_tasks_to_show: 32
    task_generator_kwargs:
      only_n_tasks: 5
training:
  seed: 0
  batch_size: 16
  learning_rate: 0.0004
  inference_mode: mean
  prior_kl_coeff: 0.0001
  task_generator:
    class: ARC
    num_pairs: 4
    num_workers: 16
    only_n_tasks: 5
  train_datasets: null
  mixed_precision: false
  total_num_steps: 1000
  eval_every_n_logs: 50
  log_every_n_steps: 100
  pairwise_kl_coeff: null
  resume_from_checkpoint: null
  online_data_augmentation: true
  gradient_accumulation_steps: 4
  save_checkpoint_every_n_logs: 100
decoder_transformer:
  _target_: src.models.utils.DecoderTransformerConfig
  max_cols: 30
  max_rows: 30
  num_layers: 6
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 8
    dropout_rate: 0.0
    mlp_dim_factor: 1.0
    emb_dim_per_head: 32
    attention_dropout_rate: 0.0
encoder_transformer:
  _target_: src.models.utils.EncoderTransformerConfig
  max_cols: 30
  max_rows: 30
  latent_dim: 64
  num_layers: 2
  variational: true
  transformer_layer:
    _target_: src.models.utils.TransformerLayerConfig
    num_heads: 4
    dropout_rate: 0.0
    mlp_dim_factor: 1.0
    emb_dim_per_head: 16
    attention_dropout_rate: 0.0
  latent_projection_bias: false
